import type { NextPage } from 'next';
import Head from 'next/head';
import { useMoralis } from 'react-moralis';
import LoginCard from '../components/LoginCard';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const { isAuthUndefined } = useMoralis();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {!isAuthUndefined ? <LoginCard /> : <p>Connected </p>}
      </main>
    </div>
  );
};

export default Home;
