import type { NextPage } from 'next';
import Head from 'next/head';
import { useMoralis } from 'react-moralis';
import Dashboard from 'src/components/common/Dashboard';
import LoginCard from 'src/components/common/LoginCard';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const { isAuthenticated } = useMoralis();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {isAuthenticated ? <Dashboard /> : <LoginCard />}
      </main>
    </div>
  );
};

export default Home;
